version: '3'

services:
  server:
    build: './server'
    entrypoint: "gunicorn -w $SERVER_MAX_WORKERS --worker-connections 10 -b 0.0.0.0:5000 app:app"
    deploy:
      mode: replicated
      replicas: $MIN_NO_OF_REPLICAS
    # ports:
    #   - "8000:5000"
    
  loadbalancer:
    build: '.'
    env_file:
      - path: ./.env
    entrypoint: "gunicorn -t 10 --worker-connections 1000 -b 0.0.0.0:5000 -k gevent load_balancer.app:app"
    # entrypoint: "hypercorn --workers=8 -b 0.0.0.0:5000 -k uvloop app:app"
    # entrypoint: "uvicorn --host 0.0.0.0 --port 5000 app3:app"
    # entrypoint: "gunicorn --worker-connections 1000 -b 0.0.0.0:5000 -k uvicorn.workers.UvicornWorker app3:app"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "4.0"
    #       memory: 500M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"

  redis:
    image: redis

  worker:
    build: '.'
    env_file:
      - path: ./.env
    entrypoint: "celery -A load_balancer.tasks worker -l debug"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loadbalancer
      - redis    

  